"""empty message

Revision ID: 1376f36eb505
Revises: 38b209ca2468
Create Date: 2023-01-26 14:09:20.449462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1376f36eb505'
down_revision = '38b209ca2468'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('game', 'decription')
    op.drop_column('game', 'types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('types', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('decription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('game', 'description')
    # ### end Alembic commands ###
