"""empty message

Revision ID: 3475ea28333c
Revises: 462227b3b0a3
Create Date: 2023-01-25 14:33:58.784218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3475ea28333c'
down_revision = '462227b3b0a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommend',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('userid', sa.BigInteger(), nullable=True),
    sa.Column('games', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommend_id'), 'recommend', ['id'], unique=False)
    op.add_column('history', sa.Column('gameid', sa.Integer(), nullable=True))
    op.drop_constraint('history_appid_fkey', 'history', type_='foreignkey')
    op.create_foreign_key(None, 'history', 'game', ['gameid'], ['id'])
    op.drop_column('history', 'appid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('appid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.create_foreign_key('history_appid_fkey', 'history', 'game', ['appid'], ['id'])
    op.drop_column('history', 'gameid')
    op.drop_index(op.f('ix_recommend_id'), table_name='recommend')
    op.drop_table('recommend')
    # ### end Alembic commands ###
