"""empty message

Revision ID: 38b209ca2468
Revises: a65d1516308b
Create Date: 2023-01-25 14:37:37.962826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b209ca2468'
down_revision = 'a65d1516308b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
