"""empty message

Revision ID: 45be65cd0f6c
Revises: 794ce9e1904d
Create Date: 2023-01-30 02:44:32.749140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45be65cd0f6c'
down_revision = '794ce9e1904d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'history', ['userid', 'gameid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='unique')
    # ### end Alembic commands ###
