"""empty message

Revision ID: 75c30e2921e8
Revises: 
Create Date: 2023-01-24 17:43:25.640999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75c30e2921e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('decription', sa.String(), nullable=True),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('positive_review', sa.Integer(), nullable=True),
    sa.Column('negative_review', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('initial_price', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('platforms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('required_age', sa.SmallInteger(), nullable=True),
    sa.Column('header_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_id'), 'game', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('persona_name', sa.String(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('userid', sa.BigInteger(), nullable=True),
    sa.Column('appid', sa.Integer(), nullable=True),
    sa.Column('playtime_total', sa.Float(), nullable=True),
    sa.Column('rtime_last_played', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appid'], ['game.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_id'), 'history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_id'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_game_id'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
