"""empty message

Revision ID: 82f234675d71
Revises: ca3ddf6e57bc
Create Date: 2023-01-29 06:38:48.444990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82f234675d71'
down_revision = 'ca3ddf6e57bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curation', sa.Column('gameid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'curation', 'game', ['gameid'], ['id'])
    op.drop_column('curation', 'games')
    op.add_column('recommend', sa.Column('gameid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recommend', 'game', ['gameid'], ['id'])
    op.drop_column('recommend', 'games')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommend', sa.Column('games', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recommend', type_='foreignkey')
    op.drop_column('recommend', 'gameid')
    op.add_column('curation', sa.Column('games', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'curation', type_='foreignkey')
    op.drop_column('curation', 'gameid')
    # ### end Alembic commands ###
