"""empty message

Revision ID: a8ced4675c21
Revises: bcf1cd47381e
Create Date: 2023-01-26 14:15:15.395215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ced4675c21'
down_revision = 'bcf1cd47381e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
