"""empty message

Revision ID: bcf1cd47381e
Revises: 1376f36eb505
Create Date: 2023-01-26 14:10:36.276644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf1cd47381e'
down_revision = '1376f36eb505'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('games', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curation_id'), 'curation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curation_id'), table_name='curation')
    op.drop_table('curation')
    # ### end Alembic commands ###
