"""empty message

Revision ID: ca3ddf6e57bc
Revises: ead8e87dcb7b
Create Date: 2023-01-26 14:16:58.840182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3ddf6e57bc'
down_revision = 'ead8e87dcb7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('required_age', sa.String(), nullable=True))
    op.drop_column('game', 'required_ag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('required_ag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('game', 'required_age')
    # ### end Alembic commands ###
